'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("vendingmachine.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0757528008680_0_A1C1_0600() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0757528008680_0_A1C1_0600", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2000_native_american_one_dollar_uncirculated_obverse_768x768() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2000-native-american-one-dollar-uncirculated-obverse-768x768", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2019_america_the_beautiful_quarters_W() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2019-america-the-beautiful-quarters-W", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2023_jefferson_nickel_uncirculated_reverse_768x768() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2023-jefferson-nickel-uncirculated-reverse-768x768", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2023_roosevelt_dime_uncirculated_reverse_768x768() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2023-roosevelt-dime-uncirculated-reverse-768x768", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _51ce_QI5dIL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("51ce+QI5dIL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _61HW2ONPf_L__AC_UF894_1000_QL80_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("61HW2ONPf-L._AC_UF894,1000_QL80_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _75752803746() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("75752803746", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _812tZPyk0fL__AC_UF894_1000_QL80_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("812tZPyk0fL._AC_UF894,1000_QL80_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _816HXqv8UiL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("816HXqv8UiL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _81EUE1oZURL__AC_UF1000_1000_QL80_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("81EUE1oZURL._AC_UF1000,1000_QL80_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _81iUuyr2R7L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("81iUuyr2R7L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _91M5DIRwhoL__AC_UF894_1000_QL80_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("91M5DIRwhoL._AC_UF894,1000_QL80_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _91NjwbVi0_L__AC_UF1000_1000_QL80_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("91NjwbVi0+L._AC_UF1000,1000_QL80_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _91Q_Hif__IL__SL1500_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("91Q+Hif--IL._SL1500_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property d5rwc5p_b7785887_7789_41db_8951_1614d3ece0bc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("d5rwc5p-b7785887-7789-41db-8951-1614d3ece0bc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GUEST_ad5ad35a_2fe7_4209_ae0d_7f71fa2d8329() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GUEST_ad5ad35a-2fe7-4209-ae0d-7f71fa2d8329", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lay_s_baked_original_potato_chips_6_25_oz_bag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lay-s-baked-original-potato-chips-6-25-oz-bag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nickel_thinkstock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nickel-thinkstock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vader() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vader", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
